# Generated by Django 4.2.2 on 2023-06-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_dtl',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='book_dtl',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('purposename', models.CharField(max_length=200, null=True)),
                ('txtonfloor', models.CharField(max_length=200, null=True)),
                ('sdate', models.DateField()),
                ('stime', models.TimeField()),
                ('etime', models.TimeField()),
                ('txtusername', models.CharField(max_length=200, null=True)),
                ('txttel', models.IntegerField(null=True)),
                ('other', models.CharField(max_length=200, null=True)),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.room_dtl')),
            ],
        ),
    ]
