# Generated by Django 4.2.2 on 2024-01-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_dtl',
            name='book_email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
